-- SEASMP — DB fix phase: dropout-score provenance, audit_logs index, CHECK constraints
--
-- This migration was generated by `prisma migrate dev --create-only` and then
-- hand-edited. The raw diff also proposed dropping/recreating the
-- notifications/user_behavior_profiles FKs, dropping the DEFAULT now() on
-- ownership_rules.updated_at / user_behavior_profiles.updated_at, and renaming
-- ownership_rules_type_path_key — all of that is pre-existing representation
-- drift between hand-written raw-SQL migrations and Prisma's own naming/
-- defaulting conventions, not an intended change, so it was removed from this
-- file. Only the changes below were actually requested.

-- ─── 1. enrollments: drop dead final_grade column, add score provenance ──────
--
-- final_grade was never written by any code path (Node or Python) — it's
-- always recomputed on the fly from grades+assessments
-- (analytics.service.ts studentStats()). Confirmed via repo-wide search
-- before dropping: no API, frontend, or analytics code reads the column
-- itself, only the identically-named *computed* API response field.
--
-- score_model_version / scored_at record which canonical model produced the
-- current dropoutRiskScore (see apps/analytics/src/services/ml_model.py
-- DROPOUT_MODEL_VERSION). The legacy dropout_service.py pipeline that used to
-- also write this column has been removed, so there is now exactly one
-- writer — these columns exist so that fact is verifiable from the data.
ALTER TABLE "enrollments"
  DROP COLUMN "final_grade",
  ADD COLUMN  "score_model_version" VARCHAR(50),
  ADD COLUMN  "scored_at" TIMESTAMPTZ;

-- ─── 2. audit_logs: composite index for the per-user windowed scan ───────────
--
-- behaviorProfiler.aggregate() runs "WHERE user_id = ? AND created_at > now()
-- - 30 days" once per active user, nightly. The existing single-column
-- user_id index works today; this composite index keeps that scan cheap as
-- audit_logs keeps growing (it is already the largest table — every /v1/
-- request writes a row here).
CREATE INDEX "audit_logs_user_id_created_at_idx" ON "audit_logs"("user_id", "created_at");

-- ─── 3. CHECK constraints for values already universally treated as 0–1 ──────
--
-- Prisma's schema language has no portable way to express CHECK constraints,
-- so these are added here directly and documented with a comment next to the
-- corresponding field in schema.prisma. Each column stays nullable where it
-- already was — the constraint allows NULL and only bounds the value when
-- present. Grade.score <= Assessment.maxScore is deliberately NOT enforced
-- here: it's a cross-table invariant a plain column CHECK can't express, and
-- stays an application-level check (assessment.service.ts submitGrade()).
ALTER TABLE "enrollments"
  ADD CONSTRAINT "enrollments_dropout_risk_score_range"
  CHECK ("dropout_risk_score" IS NULL OR ("dropout_risk_score" >= 0 AND "dropout_risk_score" <= 1));

ALTER TABLE "ownership_rules"
  ADD CONSTRAINT "ownership_rules_confidence_range"
  CHECK ("confidence" IS NULL OR ("confidence" >= 0 AND "confidence" <= 1));

ALTER TABLE "security_alerts"
  ADD CONSTRAINT "security_alerts_score_range"
  CHECK ("score" IS NULL OR ("score" >= 0 AND "score" <= 1));

ALTER TABLE "assessments"
  ADD CONSTRAINT "assessments_weight_range"
  CHECK ("weight" >= 0 AND "weight" <= 1);
